name: Build React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: '.'
        destination_repo: 'templight41/hackbangalore_freelancer_master'
        destination_branch: 'main'
        destination_folder: '/ML'
        user_email: 'armaanpasha3@gmail.com'
        user_name: 'templight41'
        commit_message: 'ML commit'